### ISSUE TITLE
引入到vue-cli项目中 报方法未定义

### ISSUE THREAD

**Issue by fungyetwah** [myronliu347/muse-model#1]
Property or method "count" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property

**Comment by myronliu347** [comment]
请给出具体的使用代码

**Comment by myronliu347** [comment]
在windows的机器上对vue 的编译会有一些问题， 所以建议在`.js` 使用 `connect` 函数链接
